### ISSUE TITLE
Move CI to Github Actions

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/nova-honeybadger#52]
It appears that we have a few tests and a travis ci yml. For consistency with other projects, I think we should move them to Github Actions.

**Comment by BethanyBerkowitz** [comment]
I may come to regret this... but I can mess with the CI 😆

**Comment by BethanyBerkowitz** [comment]
Ok, running into some issues here. I suppose I shouldn't be surprised, since this repo has not seen recent development. For the sake of transparency, I'll let y'all know that I am *far* from an expert in PHP 😆 

1. The repo wants PHP v7.1, which is [past end of life](https://www.php.net/supported-versions.php). I am having a hard time even installing 7.1 (tried both asdf and homebrew). 
2. If I use a modern version of PHP (8.2), the rest of the dependencies pretty much need to be upgraded as well. Maybe this is worth doing, but if I go ahead and upgrade a bunch of dependencies, I'm going to need to actually be able to manually test this thing rather than just figure out how to run the unit tests... so it becomes a substantially larger task than "move the CI to Github".  
3. A previous developer did [something clever around developing against laravel/nova](https://github.com/honeybadger-io/nova-honeybadger/blob/71cf599111bc080e5e01eb15e1182342ba4262d2/composer.json#L40)... looks like he somehow got a local copy of the source code but I don't see how to do this. Following [current installation instructions](https://nova.laravel.com/docs/4.0/installation.html#installing-nova-via-composer), I get an error if I try to `composer install` because I don't have a license for laravel/nova. 

So a few questions: 
1. Is it worth spending the time to get this repo humming again? I'd assume we a the very least need to upgrade PHP and dependencies and run manual testing in addition to moving the CI. It doesn't look like anyone has [installed it recently](https://packagist.org/packages/honeybadger-io/nova-honeybadger/stats), though I don't know if that's because it's out of date or just not popular or what. I also don't know if the folks who installed it in the past are using it actively or not. 
2. If we do decide to get this going again, any ideas on how to develop on this without a license? Or do we need to buy a license just for testing purposes? 

Tagging folks who've touched this repo in the past:
@shalvah @joshuap

**Comment by stympy** [comment]
In general, our policy is to only support the latest framework version for example repos, and officially supported versions for our client libraries. 

*If* we want to maintain this repo, I'd say we'd probably want to purchase a license or ask for a free license (that we'd only use for dev/test).

**Comment by shalvah** [comment]
Yeah, I don't know how much value this repo still provides. There have been no issues or PRs from the community, and, as you've pointed out, no installs since June 2021. I've never used Nova, so I'm not sure exactly what this package does that would be difficult for a Nova end user to achieve by themselves.

**Comment by joshuap** [comment]
> Yeah, I don't know how much value this repo still provides. There have been no issues or PRs from the community, and, as you've pointed out, no installs since June 2021. I've never used Nova, so I'm not sure exactly what this package does that would be difficult for a Nova end user to achieve by themselves.

It would be a fair amount of work for users to reproduce in my opinion, but yeah, not much overlap between Honeybadger users and Nova users, it seems (or they don't know this exists). I do have a Nova license, which is now in the OSS Team 1Password vault. :)

**Comment by subzero10** [comment]
I have used Nova in the past and indeed it's a great addition to Laravel users. But I was a bit surprised when I came across this repo. The nova resource that we are creating offers no more value than Honeybadger's Error Page (unless I am missing something). So, it's a nice to have feature for me, but that's all.

If we want to maintain the repo, then I think we should create another issue to focus on dependencies and then come back to this one.

**Comment by joshuap** [comment]
> I have used Nova in the past and indeed it's a great addition to Laravel users. But I was a bit surprised when I came across this repo. The nova resource that we are creating offers no more value than Honeybadger's Error Page (unless I am missing something). So, it's a nice to have feature for me, but that's all.
> 
> If we want to maintain the repo, then I think we should create another issue to focus on dependencies and then come back to this one.

The value is that this shows the errors on a *resource* page, such as a User—and it automatically filters them for errors that mention that resource in the error context. So for example, if you get a support ticket from a user and go to their dashboard in nova, you'd be able to see if they've encountered any errors without going to Honeybadger.

**Comment by subzero10** [comment]
> > I have used Nova in the past and indeed it's a great addition to Laravel users. But I was a bit surprised when I came across this repo. The nova resource that we are creating offers no more value than Honeybadger's Error Page (unless I am missing something). So, it's a nice to have feature for me, but that's all.
> > If we want to maintain the repo, then I think we should create another issue to focus on dependencies and then come back to this one.
> 
> The value is that this shows the errors on a _resource_ page, such as a User—and it automatically filters them for errors that mention that resource in the error context. So for example, if you get a support ticket from a user and go to their page in nova, you'd be able to see if they've encountered any errors without going to Honeybadger.

Ah, gotcha. Indeed, as a previous Nova user my self, that would pretty neat to have.

**Comment by BethanyBerkowitz** [comment]
Ok folks, so it sounds like if we revived this repo and Laravel Nova users actually used it, it would provide significant value. However, it doesn't seem like it has gotten a lot of traction, as evidenced by lack of downloads. So I see two options here: 

1. Update and revive this repo. Actively work on getting folks to use it (via advertising or whatever). This could make sense if there are a significant number of users out there who would love to use this but just don't know it exists. 
2. Archive this repo. This makes sense if we think the lack of engagement is likely to continue (due to lack of overlap between Honeybadger customers and Nova users, for example). 

This is a business decision more than a technical one. Perhaps @stympy and/or @joshuap can decide what to do?

**Comment by stympy** [comment]
I think it makes sense to archive the repo.

**Comment by BethanyBerkowitz** [comment]
> I think it makes sense to archive the repo.

I'm fine with this! @subzero10 does this sound ok you?

**Comment by subzero10** [comment]
Yes! I'm a bit sad that we are leaving behind a project, but I also think it's the correct decision at this time.
